// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package favoritepb

import (
	context "context"
	"final-SA-Golang/favorites_microservice/cmd/web"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FavoriteServiceClient is the client API for FavoriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavoriteServiceClient interface {
	CreateFavorite(ctx context.Context, in *CreateFavoriteRequest, opts ...grpc.CallOption) (*CreateFavoriteResponse, error)
	DeleteFavorite(ctx context.Context, in *DeleteFavoriteRequest, opts ...grpc.CallOption) (*DeleteFavoriteResponse, error)
	GetFavorite(ctx context.Context, in *GetFavoriteRequest, opts ...grpc.CallOption) (FavoriteService_GetFavoriteClient, error)
}

type favoriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFavoriteServiceClient(cc grpc.ClientConnInterface) FavoriteServiceClient {
	return &favoriteServiceClient{cc}
}

func (c *favoriteServiceClient) CreateFavorite(ctx context.Context, in *CreateFavoriteRequest, opts ...grpc.CallOption) (*CreateFavoriteResponse, error) {
	out := new(CreateFavoriteResponse)
	err := c.cc.Invoke(ctx, "/favoritepb.FavoriteService/CreateFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) DeleteFavorite(ctx context.Context, in *DeleteFavoriteRequest, opts ...grpc.CallOption) (*DeleteFavoriteResponse, error) {
	out := new(DeleteFavoriteResponse)
	err := c.cc.Invoke(ctx, "/favoritepb.FavoriteService/DeleteFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) GetFavorite(ctx context.Context, in *GetFavoriteRequest, opts ...grpc.CallOption) (FavoriteService_GetFavoriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &FavoriteService_ServiceDesc.Streams[0], "/favoritepb.FavoriteService/GetFavorite", opts...)
	if err != nil {
		return nil, err
	}
	x := &favoriteServiceGetFavoriteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FavoriteService_GetFavoriteClient interface {
	Recv() (*GetFavoriteResponse, error)
	grpc.ClientStream
}

type favoriteServiceGetFavoriteClient struct {
	grpc.ClientStream
}

func (x *favoriteServiceGetFavoriteClient) Recv() (*GetFavoriteResponse, error) {
	m := new(GetFavoriteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FavoriteServiceServer is the server API for FavoriteService service.
// All implementations must embed UnimplementedFavoriteServiceServer
// for forward compatibility
type FavoriteServiceServer interface {
	CreateFavorite(context.Context, *CreateFavoriteRequest) (*CreateFavoriteResponse, error)
	DeleteFavorite(context.Context, *DeleteFavoriteRequest) (*DeleteFavoriteResponse, error)
	GetFavorite(*GetFavoriteRequest, FavoriteService_GetFavoriteServer) error
	mustEmbedUnimplementedFavoriteServiceServer()
}

// UnimplementedFavoriteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFavoriteServiceServer struct {
}

func (UnimplementedFavoriteServiceServer) CreateFavorite(context.Context, *CreateFavoriteRequest) (*CreateFavoriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFavorite not implemented")
}
func (UnimplementedFavoriteServiceServer) DeleteFavorite(context.Context, *DeleteFavoriteRequest) (*DeleteFavoriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFavorite not implemented")
}
func (UnimplementedFavoriteServiceServer) GetFavorite(*GetFavoriteRequest, FavoriteService_GetFavoriteServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFavorite not implemented")
}
func (UnimplementedFavoriteServiceServer) mustEmbedUnimplementedFavoriteServiceServer() {}

// UnsafeFavoriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavoriteServiceServer will
// result in compilation errors.
type UnsafeFavoriteServiceServer interface {
	mustEmbedUnimplementedFavoriteServiceServer()
}

func RegisterFavoriteServiceServer(s grpc.ServiceRegistrar, srv *main.Server) {
	s.RegisterService(&FavoriteService_ServiceDesc, srv)
}

func _FavoriteService_CreateFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).CreateFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/favoritepb.FavoriteService/CreateFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).CreateFavorite(ctx, req.(*CreateFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_DeleteFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).DeleteFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/favoritepb.FavoriteService/DeleteFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).DeleteFavorite(ctx, req.(*DeleteFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_GetFavorite_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFavoriteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FavoriteServiceServer).GetFavorite(m, &favoriteServiceGetFavoriteServer{stream})
}

type FavoriteService_GetFavoriteServer interface {
	Send(*GetFavoriteResponse) error
	grpc.ServerStream
}

type favoriteServiceGetFavoriteServer struct {
	grpc.ServerStream
}

func (x *favoriteServiceGetFavoriteServer) Send(m *GetFavoriteResponse) error {
	return x.ServerStream.SendMsg(m)
}

// FavoriteService_ServiceDesc is the grpc.ServiceDesc for FavoriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavoriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "favoritepb.FavoriteService",
	HandlerType: (*FavoriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFavorite",
			Handler:    _FavoriteService_CreateFavorite_Handler,
		},
		{
			MethodName: "DeleteFavorite",
			Handler:    _FavoriteService_DeleteFavorite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFavorite",
			Handler:       _FavoriteService_GetFavorite_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "favoritepb/favorite.proto",
}
