// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: favoritepb/favorite.proto

package favoritepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Favorite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SongId int64 `protobuf:"varint,3,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
}

func (x *Favorite) Reset() {
	*x = Favorite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoritepb_favorite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Favorite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favorite) ProtoMessage() {}

func (x *Favorite) ProtoReflect() protoreflect.Message {
	mi := &file_favoritepb_favorite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favorite.ProtoReflect.Descriptor instead.
func (*Favorite) Descriptor() ([]byte, []int) {
	return file_favoritepb_favorite_proto_rawDescGZIP(), []int{0}
}

func (x *Favorite) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Favorite) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Favorite) GetSongId() int64 {
	if x != nil {
		return x.SongId
	}
	return 0
}

type CreateFavoriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Favorite *Favorite `protobuf:"bytes,1,opt,name=favorite,proto3" json:"favorite,omitempty"`
}

func (x *CreateFavoriteRequest) Reset() {
	*x = CreateFavoriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoritepb_favorite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFavoriteRequest) ProtoMessage() {}

func (x *CreateFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favoritepb_favorite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFavoriteRequest.ProtoReflect.Descriptor instead.
func (*CreateFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_favoritepb_favorite_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFavoriteRequest) GetFavorite() *Favorite {
	if x != nil {
		return x.Favorite
	}
	return nil
}

type CreateFavoriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateFavoriteResponse) Reset() {
	*x = CreateFavoriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoritepb_favorite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFavoriteResponse) ProtoMessage() {}

func (x *CreateFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favoritepb_favorite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFavoriteResponse.ProtoReflect.Descriptor instead.
func (*CreateFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_favoritepb_favorite_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFavoriteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFavoriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=u_id,json=uId,proto3" json:"u_id,omitempty"`
	SId int64 `protobuf:"varint,2,opt,name=s_id,json=sId,proto3" json:"s_id,omitempty"`
}

func (x *DeleteFavoriteRequest) Reset() {
	*x = DeleteFavoriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoritepb_favorite_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavoriteRequest) ProtoMessage() {}

func (x *DeleteFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favoritepb_favorite_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavoriteRequest.ProtoReflect.Descriptor instead.
func (*DeleteFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_favoritepb_favorite_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFavoriteRequest) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *DeleteFavoriteRequest) GetSId() int64 {
	if x != nil {
		return x.SId
	}
	return 0
}

type DeleteFavoriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFavoriteResponse) Reset() {
	*x = DeleteFavoriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoritepb_favorite_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavoriteResponse) ProtoMessage() {}

func (x *DeleteFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favoritepb_favorite_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavoriteResponse.ProtoReflect.Descriptor instead.
func (*DeleteFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_favoritepb_favorite_proto_rawDescGZIP(), []int{4}
}

type GetFavoriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetFavoriteRequest) Reset() {
	*x = GetFavoriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoritepb_favorite_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoriteRequest) ProtoMessage() {}

func (x *GetFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favoritepb_favorite_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoriteRequest.ProtoReflect.Descriptor instead.
func (*GetFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_favoritepb_favorite_proto_rawDescGZIP(), []int{5}
}

func (x *GetFavoriteRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFavoriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Favorite *Favorite `protobuf:"bytes,1,opt,name=favorite,proto3" json:"favorite,omitempty"`
}

func (x *GetFavoriteResponse) Reset() {
	*x = GetFavoriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoritepb_favorite_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoriteResponse) ProtoMessage() {}

func (x *GetFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favoritepb_favorite_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoriteResponse.ProtoReflect.Descriptor instead.
func (*GetFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_favoritepb_favorite_proto_rawDescGZIP(), []int{6}
}

func (x *GetFavoriteResponse) GetFavorite() *Favorite {
	if x != nil {
		return x.Favorite
	}
	return nil
}

var File_favoritepb_favorite_proto protoreflect.FileDescriptor

var file_favoritepb_favorite_proto_rawDesc = []byte{
	0x0a, 0x19, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x2f, 0x66, 0x61, 0x76,
	0x6f, 0x72, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x66, 0x61, 0x76,
	0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x22, 0x4c, 0x0a, 0x08, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x69, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x6f, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x6f, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x08, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x46, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x08, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x22, 0x28, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x11, 0x0a, 0x04, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x49, 0x64, 0x12, 0x11, 0x0a, 0x04, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x66, 0x61, 0x76,
	0x6f, 0x72, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x08, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x32, 0x9b, 0x02, 0x0a, 0x0f,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x59, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74,
	0x65, 0x12, 0x21, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x66,
	0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x5c, 0x62, 0x7a, 0x68, 0x6f, 0x6c, 0x6d, 0x79, 0x72,
	0x7a, 0x61, 0x5c, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x2d, 0x53, 0x41, 0x2d, 0x47, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x5c, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x3b, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_favoritepb_favorite_proto_rawDescOnce sync.Once
	file_favoritepb_favorite_proto_rawDescData = file_favoritepb_favorite_proto_rawDesc
)

func file_favoritepb_favorite_proto_rawDescGZIP() []byte {
	file_favoritepb_favorite_proto_rawDescOnce.Do(func() {
		file_favoritepb_favorite_proto_rawDescData = protoimpl.X.CompressGZIP(file_favoritepb_favorite_proto_rawDescData)
	})
	return file_favoritepb_favorite_proto_rawDescData
}

var file_favoritepb_favorite_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_favoritepb_favorite_proto_goTypes = []interface{}{
	(*Favorite)(nil),               // 0: favoritepb.Favorite
	(*CreateFavoriteRequest)(nil),  // 1: favoritepb.CreateFavoriteRequest
	(*CreateFavoriteResponse)(nil), // 2: favoritepb.CreateFavoriteResponse
	(*DeleteFavoriteRequest)(nil),  // 3: favoritepb.DeleteFavoriteRequest
	(*DeleteFavoriteResponse)(nil), // 4: favoritepb.DeleteFavoriteResponse
	(*GetFavoriteRequest)(nil),     // 5: favoritepb.GetFavoriteRequest
	(*GetFavoriteResponse)(nil),    // 6: favoritepb.GetFavoriteResponse
}
var file_favoritepb_favorite_proto_depIdxs = []int32{
	0, // 0: favoritepb.CreateFavoriteRequest.favorite:type_name -> favoritepb.Favorite
	0, // 1: favoritepb.GetFavoriteResponse.favorite:type_name -> favoritepb.Favorite
	1, // 2: favoritepb.FavoriteService.CreateFavorite:input_type -> favoritepb.CreateFavoriteRequest
	3, // 3: favoritepb.FavoriteService.DeleteFavorite:input_type -> favoritepb.DeleteFavoriteRequest
	5, // 4: favoritepb.FavoriteService.GetFavorite:input_type -> favoritepb.GetFavoriteRequest
	2, // 5: favoritepb.FavoriteService.CreateFavorite:output_type -> favoritepb.CreateFavoriteResponse
	4, // 6: favoritepb.FavoriteService.DeleteFavorite:output_type -> favoritepb.DeleteFavoriteResponse
	6, // 7: favoritepb.FavoriteService.GetFavorite:output_type -> favoritepb.GetFavoriteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_favoritepb_favorite_proto_init() }
func file_favoritepb_favorite_proto_init() {
	if File_favoritepb_favorite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_favoritepb_favorite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Favorite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favoritepb_favorite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFavoriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favoritepb_favorite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFavoriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favoritepb_favorite_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFavoriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favoritepb_favorite_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFavoriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favoritepb_favorite_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFavoriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favoritepb_favorite_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFavoriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_favoritepb_favorite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_favoritepb_favorite_proto_goTypes,
		DependencyIndexes: file_favoritepb_favorite_proto_depIdxs,
		MessageInfos:      file_favoritepb_favorite_proto_msgTypes,
	}.Build()
	File_favoritepb_favorite_proto = out.File
	file_favoritepb_favorite_proto_rawDesc = nil
	file_favoritepb_favorite_proto_goTypes = nil
	file_favoritepb_favorite_proto_depIdxs = nil
}
